#!/user/bin/env bash
# installs the ufw firewall and setsup a few rules

sudo apt-get install ufw
sudo ufw default deny incoming
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw enable
