#!/bin/bash

# Check if Gunicorn process is running
if pgrep gunicorn >/dev/null 2>&1; then
    # Get the process ID (PID) of Gunicorn
    gunicorn_pid=$(pgrep gunicorn)

    # Send the HUP signal to gracefully reload Gunicorn
    kill -HUP "$gunicorn_pid"

    echo "Gunicorn reloaded gracefully."
else
    echo "Gunicorn is not running."
fi

