#!/usr/bin/env bash
# Kill gunicorn worker processe gracefully, with no downtime
# kill -HUP gunicorn
gunicorn_pid=$(pgrep gunicorn)

if [ -n "$gunicorn_pid" ]; then
    # Send the HUP signal to gracefully reload Gunicorn
    kill -HUP "$gunicorn_pid"
    echo "Gunicorn reloaded gracefully."
else
    echo "Gunicorn is not running."
fi
